name: CI

on:
  push:
    branches: [main, alpha, beta]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🟨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Install dependencies
        run: pnpm install

      - name: 🧪 Test
        run: pnpm test

      - name: 📦 Release
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status.

          pnpm -r --workspace-concurrency=1 exec -- npx --no-install semantic-release
          pnpm -r publish
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
